Repository Inlyne-Project/inlyne, pull requests merged in 2023-05, with the labels that each got.

#112 Basic YAML front-matter support
  Cargo.lock
  Cargo.toml
  src/interpreter.rs
  src/utils.rs
Labels: C-enhancement, A-table

#115 Add ability to scroll with PageUp/PageDown
  src/keybindings/defaults.rs
  src/keybindings/mod.rs
  src/main.rs
Labels: C-enhancement, A-keybinding

#116 Add a test for all CLI options
  src/opts/tests.rs
Labels: A-CLI

#118 Make invalid states unreachable
  src/keybindings/action.rs
  src/keybindings/defaults.rs
  src/keybindings/mod.rs
  src/keybindings/serialization.rs
  src/keybindings/tests.rs
  src/main.rs
Labels: C-refactor, A-keybinding, A-Action

#109 Add repology badge for package manager installation
  README.md
Labels: C-documentation

#114 Rename sample TOML file
  .github/workflows/release.yml
  README.md
  inlyne.sample.toml
  inlyne.toml.sample
Labels: C-documentation, C-refactor

#105 [WIP] Switch to glyphon/cosmic text from wgpu-glyph/ab-glyph
  Cargo.lock
  Cargo.toml
  README.md
  src/fonts.rs
  src/image/mod.rs
  src/interpreter.rs
  src/main.rs
  src/opts/mod.rs
  src/positioner.rs
  src/renderer.rs
  src/table.rs
  src/text.rs
  src/utils.rs
Labels: C-enhancement, C-refactor, A-font

#119 Fix outdated zbus bug
  Cargo.lock
Labels: C-bug

#117 Support parsing shortcodes
  Cargo.lock
  Cargo.toml
  src/utils.rs
Labels: C-enhancement, A-font

#113 Generate shell completions through a `cargo-xtask` task
  .cargo/config.toml
  .github/workflows/CI.yml
  .github/workflows/release.yml
  Cargo.lock
  Cargo.toml
  completions/README.md
  completions/_inlyne
  completions/_inlyne.ps1
  completions/inlyne.bash
  completions/inlyne.elv
  completions/inlyne.fish
  src/opts/cli.rs
  src/opts/mod.rs
  xtask/Cargo.toml
  xtask/src/gen.rs
  xtask/src/main.rs
Labels: C-refactor, !!breaking change!!, A-CLI

#120 Fork glyphon and cosmic-text
  Cargo.lock
  Cargo.toml
  src/renderer.rs
Labels: C-bug, A-font

#124 `inlyne.sample.toml` -> `inlyne.default.toml`
  .github/workflows/release.yml
  README.md
  inlyne.default.toml
  src/opts/config.rs
Labels: C-documentation

#127 Add support for custom syntax themes
  inlyne.default.toml
  src/color.rs
  src/interpreter.rs
  src/main.rs
  src/opts/config.rs
  src/opts/mod.rs
  src/opts/tests.rs
  src/utils.rs
  tests/assets/sample.tmTheme
Labels: C-enhancement, A-config, A-theme

#126 Anchorize footnotes
  src/interpreter.rs
Labels: C-enhancement

#128 Fix footnote numbered list
  src/interpreter.rs
  src/main.rs
Labels: C-bug

#129 Use taffy for tables
  Cargo.lock
  Cargo.toml
  src/image/mod.rs
  src/main.rs
  src/positioner.rs
  src/renderer.rs
  src/table.rs
  src/text.rs
  src/utils.rs
Labels: C-enhancement, A-table

#132 Interpreter testing
  src/debug_impls.rs
  src/image/mod.rs
  src/interpreter/html.rs
  src/interpreter/mod.rs
  src/interpreter/snapshots/inlyne__interpreter__tests__footnotes_list_prefix.snap
  src/interpreter/tests.rs
  src/main.rs
  src/positioner.rs
  src/text.rs
Labels: C-refactor

#134 Add a basic `CONTRIBUTING.md` doc
  CONTRIBUTING.md
Labels: C-documentation

#133 Checklists shouldn't have a text prefix
  src/interpreter/mod.rs
  src/interpreter/snapshots/inlyne__interpreter__tests__checklist_has_no_text_prefix.snap
  src/interpreter/tests.rs
Labels: C-bug, A-lists
