Repository Inlyne-Project/inlyne, pull requests merged in 2024-03, with the labels that each got.

#268 Tweak CI run trigger to run on fewer pushes
  .github/workflows/CI.yml
Labels: C-refactor, A-CI

#269 Flesh out history
  inlyne.default.toml
  src/history.rs
  src/keybindings/action.rs
  src/keybindings/defaults.rs
  src/keybindings/serialization.rs
  src/main.rs
Labels: C-refactor

#270 Ensure that we can always deserialize the default keybindings
  src/keybindings/keybindings.rs
  src/keybindings/tests.rs
Labels: A-keybinding

#271 Exclude unsupported package repos from repology badge
  README.md
Labels: C-documentation

#272 Update non-breaking (for us) dependencies
  Cargo.lock
  Cargo.toml
  src/image/decode.rs
  src/image/mod.rs
  src/opts/tests/error_msg.rs
  xtask/Cargo.toml
Labels: A-deps

#273 test: Improve test coverage
  assets/test_data/rgb8.qoi
  assets/test_data/rgba8.qoi
  src/image/tests.rs
  src/interpreter/snapshots/inlyne__interpreter__tests__collapsed_section.snap
  src/interpreter/tests.rs
Labels: C-refactor

#274 fix: Update the title on file changes
  src/main.rs
  src/utils.rs
Labels: C-bug

#279 Fix crash when rendering headerless table
  src/renderer.rs
Labels: C-bug, A-table

#280 doc(readme): Improve installation docs
  README.md
Labels: C-documentation

#284 CLI rewrite
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/opts/cli.rs
  src/opts/mod.rs
  src/opts/tests/parse.rs
  xtask/src/gen.rs
Labels: C-refactor, !!breaking change!!, A-CLI

#286 refactor: Fully customize our panic hook
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/panic_hook.rs
Labels: C-refactor

#287 refactor(config): Improve keybindings config definition ergonomics
  inlyne.default.toml
  src/keybindings/serialization.rs
  src/keybindings/tests.rs
Labels: C-refactor, A-keybinding, A-config

#285 Add the automatic creation of config files and the ability to open them with the CLI.
  src/main.rs
  src/opts/cli.rs
  src/opts/config.rs
  src/opts/mod.rs
Labels: C-enhancement, A-CLI, A-config

#288 fix: Remove 0 character long selections
  src/text.rs
Labels: C-bug

#289 feat: Setup initial metrics infrastructure
  Cargo.lock
  Cargo.toml
  src/image/decode.rs
  src/image/mod.rs
  src/main.rs
  src/metrics/counter.rs
  src/metrics/gauge.rs
  src/metrics/hist.rs
  src/metrics/log_recorder.rs
  src/metrics/mod.rs
  src/opts/config.rs
  src/opts/mod.rs
  src/opts/tests/parse.rs
  src/renderer.rs
Labels: C-enhancement
