Repository Inlyne-Project/inlyne, pull requests merged in 2024-04, with the labels that each got.

#290 feat: Add window position and size configuration options.
  inlyne.default.toml
  src/main.rs
  src/opts/cli.rs
  src/opts/config.rs
  src/opts/mod.rs
  src/opts/tests/parse.rs
Labels: A-CLI, A-config

#293 chore: Add a `.desktop` file
  assets/inlyne.desktop
Labels: C-enhancement, P-linux

#296 refactor: Switch from `reqwest` to `ureq`
  Cargo.lock
  Cargo.toml
  src/image/mod.rs
  src/utils.rs
Labels: C-refactor

#297 chore: Resolve beta clippy lints
  src/interpreter/mod.rs
  src/main.rs
Labels: C-refactor

#300 Simple dependency updates
  Cargo.lock
  Cargo.toml
  src/interpreter/mod.rs
  xtask/Cargo.toml
Labels: A-deps

#301 chore(deps): Let `cargo` update the lockfile
  Cargo.lock
Labels: A-deps

#295 Add double and triple click selection
  src/main.rs
  src/renderer.rs
  src/selection.rs
  src/text.rs
  src/utils.rs
Labels: C-enhancement

#312 refactor: Move element bound render toggle to config
  Cargo.toml
  src/opts/config.rs
  src/opts/mod.rs
  src/renderer.rs
Labels: C-refactor

#317 Tweak .desktop file
  .github/workflows/release.yml
  assets/inlyne.desktop
Labels: A-releases

#320 refactor(tests): Drop wiremock
  Cargo.lock
  Cargo.toml
  src/interpreter/tests.rs
  src/main.rs
  src/test_utils.rs
Labels: C-refactor

#321 refactor: Simplify file server
  src/test_utils.rs
Labels: C-refactor
