Repository Inlyne-Project/inlyne, pull requests merged in 2024-02, with the labels that each got.

#226 Make underlines and strikethroughs respect align
  src/renderer.rs
  src/text.rs
Labels: C-bug, A-font

#227 Switch to `comrak`'s anchorizer
  src/interpreter/mod.rs
  src/interpreter/snapshots/inlyne__interpreter__tests__unique_anchors.snap
  src/interpreter/tests.rs
Labels: C-bug

#230 Switch to more typical zoom-in zoom-out hotkeys
  src/keybindings/defaults.rs
Labels: !!breaking change!!, A-keybinding, A-config

#235 Make the HTML interpreter more approachable
  Cargo.lock
  Cargo.toml
  src/interpreter/element.rs
  src/interpreter/html.rs
  src/interpreter/mod.rs
  src/interpreter/snapshots/inlyne__interpreter__tests__blockquote.snap
  src/interpreter/snapshots/inlyne__interpreter__tests__horizontal_ruler.snap
  src/interpreter/snapshots/inlyne__interpreter__tests__kbd_tag.snap
  src/interpreter/snapshots/inlyne__interpreter__tests__small_text.snap
  src/interpreter/snapshots/inlyne__interpreter__tests__text_styles.snap
  src/interpreter/tag_name.rs
  src/interpreter/tests.rs
  src/positioner.rs
  src/text.rs
Labels: C-bug, C-enhancement, C-refactor, A-interpreter

#238 Allow for `px` suffix on pixel length
  src/image/mod.rs
  src/image/tests.rs
  src/interpreter/html.rs
  src/interpreter/mod.rs
  src/interpreter/snapshots/inlyne__interpreter__tests__centered_image_with_size_align_and_link.snap
  src/interpreter/tests.rs
  src/keybindings/tests.rs
  src/opts/tests/error_msg.rs
Labels: C-bug, A-image

#239 Reorganize `interpreter`'s HTML code
  src/interpreter/html.rs
  src/interpreter/html/attr.rs
  src/interpreter/html/element.rs
  src/interpreter/html/mod.rs
  src/interpreter/html/style.rs
  src/interpreter/html/tag_name.rs
  src/interpreter/mod.rs
Labels: C-refactor, A-interpreter

#236 Add support for color-scheme dependent pictures
  Cargo.lock
  Cargo.toml
  src/image/mod.rs
  src/interpreter/html/attr.rs
  src/interpreter/html/element.rs
  src/interpreter/html/mod.rs
  src/interpreter/html/picture.rs
  src/interpreter/html/tag_name.rs
  src/interpreter/mod.rs
  src/interpreter/tests.rs
  src/main.rs
  src/opts/mod.rs
  src/opts/tests/parse.rs
Labels: C-enhancement, A-image, A-theme, A-interpreter

#243 Add clipboard support for wayland
  .github/workflows/CI.yml
  Cargo.lock
  Cargo.toml
  src/clipboard.rs
  src/main.rs
Labels: C-enhancement

#245 v0.4.0 release :tada:
  Cargo.lock
  Cargo.toml
  README.md
  assets/img/example.png
  completions/_inlyne
  completions/_inlyne.ps1
  completions/inlyne.bash
  completions/inlyne.fish
Labels: A-releases

#250 Enable `fontconfig` feature for transitive `fontdb` dep
  Cargo.lock
  Cargo.toml
Labels: C-bug, A-font, C-released-regression

#251 Update repository link to use new org
  Cargo.toml
Labels: C-documentation

#252 Prepare the v0.4.1 release
  Cargo.lock
  Cargo.toml
Labels: A-releases

#253 Add `write-all` permission for release workflow
  .github/workflows/release.yml
Labels: A-CI

#256 fix(links): ignore the case when look-up for an anchor
  src/main.rs
Labels: C-bug
