Repository Inlyne-Project/inlyne, pull requests merged in 2024-06, with the labels that each got.

#336 refactor: Update `human_panic` to v2.0.0
  Cargo.lock
  Cargo.toml
  src/panic_hook.rs
Labels: A-deps

#339 fix: selection bugs
  src/main.rs
  src/renderer.rs
Labels: C-bug

#341 Badge and improve code coverage
  README.md
  assets/img/example.png
  src/opts/cli.rs
  src/opts/tests/parse.rs
  src/panic_hook.rs
Labels: C-refactor

#345 refactor: Speed up graceful image failure test
  Cargo.toml
  src/image/mod.rs
Labels: C-refactor, A-font

#348 Fix test perf regression and new beta warning
  Cargo.toml
Labels: C-refactor
